spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/woniu_store?characterEncoding=utf8&ServerTimeZone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: luguangyu1
    hikari:
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 30
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: shiki
    password: luguangyu1
    virtual-host: /shiki
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1

server:
  port: 8081


mybatis:
  type-aliases-package: org.shiki.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

