spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/woniu_store?characterEncoding=utf8&ServerTimeZone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: luguangyu1
    hikari:
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接最大存活时间 默认 10 * 60 * 1000 （10分钟）
      idle-timeout: 1800000
      #连接池最大连接数 默认10
      maximum-pool-size: 30
      #从连接池返回的连接自动提交
      auto-commit: true
      #最大存活时间 默认30分钟 ，0永远存huo
      max-lifetime: 1800000
      #连接超时时间 默认30秒
      connection-timeout: 30000
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8081


mybatis:
  type-aliases-package: org.shiki.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

